server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver


    url: jdbc:mysql://localhost:3306/todo_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true


    username: root
    password: 12345678


  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 10s

#  mvc:
#    view:1
#      suffix: .jsp
#      prefix: /WEB-INF/jsp/
jedis:
  #    链接池
  pool:
    #       最大连接数（负值表示没有限制）
    max-active: 8
    #       最大阻塞等待时间（负值表示没有限制）
    max-wait: 1
    #       最大空闲链接
    max-idle: 8
    #       最小空闲链接
    min-idle: 0
  ###FREEMARKER (FreeMarkerAutoConfiguration)


logging:
  config: classpath:./logConfig.xml

mybatis:
  #打印mybatis日志
  configuration:
    #org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
    #org.apache.ibatis.logging.log4j2.Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

myConfig:
  redis:
    # redis中，登录人权限相关的有效时间
    timeout: 1800

  file:
    uploadUrl: /www/wwwroot/static/
